//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektWypozyczalnia_Gola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klient()
        {
            this.wypozyczenies = new HashSet<wypozyczenie>();
        }
    
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string ulica { get; set; }
        public string numer_domu { get; set; }
        public string miasto { get; set; }
        public string kod { get; set; }
        public string nip { get; set; }
        public string nr_telefonu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wypozyczenie> wypozyczenies { get; set; }
    }
}
