//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektWypozyczalnia_Gola.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WypAutEntities : DbContext
    {
        public WypAutEntities()
            : base("name=WypAutEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategoria> kategorias { get; set; }
        public virtual DbSet<klient> klients { get; set; }
        public virtual DbSet<pracownik> pracowniks { get; set; }
        public virtual DbSet<samochod> samochods { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<wypozyczalnia> wypozyczalnias { get; set; }
        public virtual DbSet<wypozyczenie> wypozyczenies { get; set; }
        public virtual DbSet<wypozyczenie_has_pracownik> wypozyczenie_has_pracownik { get; set; }
    }
}
