//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektWypozyczalnia_Gola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class samochod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public samochod()
        {
            this.wypozyczenies = new HashSet<wypozyczenie>();
        }
    
        public int id { get; set; }
        public int wypozyczalnia_id { get; set; }
        public int kategoria_id { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public System.DateTime rok_prod { get; set; }
        public string kolor { get; set; }
        public int poj_silnika { get; set; }
        public string opis { get; set; }
        public Nullable<decimal> cena { get; set; }
        public Nullable<int> ilosc_drzwi { get; set; }
    
        public virtual kategoria kategoria { get; set; }
        public virtual wypozyczalnia wypozyczalnia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wypozyczenie> wypozyczenies { get; set; }
    }
}
