//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektWypozyczalnia_Gola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wypozyczenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wypozyczenie()
        {
            this.wypozyczenie_has_pracownik = new HashSet<wypozyczenie_has_pracownik>();
        }
    
        public int id { get; set; }
        public int samochod_id { get; set; }
        public int klient_id { get; set; }
        public Nullable<System.DateTime> data_wypozyczenia { get; set; }
        public Nullable<System.DateTime> data_konca_wypoz { get; set; }
        public Nullable<System.DateTime> data_oddania { get; set; }
        public Nullable<decimal> cena { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual samochod samochod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wypozyczenie_has_pracownik> wypozyczenie_has_pracownik { get; set; }
    }
}
