//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektWypozyczalnia_Gola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wypozyczenie_has_pracownik
    {
        public int wypozyczenie_id { get; set; }
        public int pracownik_id { get; set; }
        public Nullable<bool> wyp_odd { get; set; }
    
        public virtual pracownik pracownik { get; set; }
        public virtual wypozyczenie wypozyczenie { get; set; }
    }
}
